-- Generated by tools/build_bridge.py - do not edit by hand.
-- npcId -> { key = <AtlasLoot loot-table key>, instance = <name> }.

LootTracker_NPCBridge = {}

LootTracker_NPCBridge[638] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Marisa du'Paige", instance = "The Deadmines" }
LootTracker_NPCBridge[639] = { items = { 5193, 5202, 10399, 5191 }, instance = "The Deadmines" }
LootTracker_NPCBridge[642] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Sneed's Shredder", instance = "The Deadmines" }
LootTracker_NPCBridge[643] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Sneed", instance = "The Deadmines" }
LootTracker_NPCBridge[644] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Rhahk'Zor", instance = "The Deadmines" }
LootTracker_NPCBridge[645] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Cookie", instance = "The Deadmines" }
LootTracker_NPCBridge[646] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Mr. Smite", instance = "The Deadmines" }
LootTracker_NPCBridge[647] = { items = { 10403, 5200, 5201 }, instance = "The Deadmines" }
LootTracker_NPCBridge[1663] = { keys = { "TheStockade" }, boss = "Dextren Ward", instance = "The Stockade" }
LootTracker_NPCBridge[1666] = { keys = { "TheStockade" }, boss = "Kam Deepfury", instance = "The Stockade" }
LootTracker_NPCBridge[1696] = { keys = { "TheStockade" }, boss = "Targorr the Dread", instance = "The Stockade" }
LootTracker_NPCBridge[1716] = { keys = { "TheStockade" }, boss = "Bazil Thredd", instance = "The Stockade" }
LootTracker_NPCBridge[1717] = { keys = { "TheStockade" }, boss = "Hamhock", instance = "The Stockade" }
LootTracker_NPCBridge[1720] = { keys = { "TheStockade" }, boss = "Bruegal Ironknuckle", instance = "The Stockade" }
LootTracker_NPCBridge[1763] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Gilnid", instance = "The Deadmines" }
LootTracker_NPCBridge[1853] = { key = "SCHOLODarkmasterGandling", instance = "Scholomance" }
LootTracker_NPCBridge[2748] = { key = "UldArchaedas", instance = "Uldaman" }
LootTracker_NPCBridge[3586] = { keys = { "TheDeadmines1", "TheDeadmines2" }, boss = "Miner Johnson", instance = "The Deadmines" }
LootTracker_NPCBridge[3653] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Kresh", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3654] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Mutanus the Devourer", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3669] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Lord Cobrahn", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3670] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Lord Pythas", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3671] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Lady Anacondra", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3673] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Lord Serpentis", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3674] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Skum", instance = "Wailing Caverns" }
LootTracker_NPCBridge[3886] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Razorclaw the Butcher", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[3887] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Baron Silverlaine", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[3914] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Rethilgore", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[3927] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Wolf Master Nandos", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[3974] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "Houndmaster Loksey", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[3975] = { items = { 7719, 7718, 10330, 7717 }, instance = "Scarlet Monastery" }
LootTracker_NPCBridge[3976] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "Scarlet Commander Mograine", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[3977] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "High Inquisitor Whitemane", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[3983] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "Interrogator Vishas", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[4274] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Fenrus the Devourer", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[4275] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Archmage Arugal", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[4278] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Commander Springvale", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[4279] = { keys = { "ShadowfangKeep1", "ShadowfangKeep2" }, boss = "Odo the Blindwatcher", instance = "Shadowfang Keep" }
LootTracker_NPCBridge[4420] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Overlord Ramtusk", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[4421] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Charlga Razorflank", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[4424] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Aggem Thorncurse", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[4425] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Agathelos the Raging", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[4428] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Death Speaker Jargba", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[4516] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Earthcaller Halmgar", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[4542] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "High Inquisitor Fairbanks", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[4543] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "Bloodmage Thalnos", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[4829] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Aku'mai", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[4830] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Old Serra'kis", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[4831] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Lady Sarevess", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[4832] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Twilight Lord Kelris", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[4854] = { key = "UldGrimlok", instance = "Uldaman" }
LootTracker_NPCBridge[4887] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Ghamoo-ra", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[5709] = { key = "STEranikus", instance = "The Sunken Temple" }
LootTracker_NPCBridge[5710] = { key = "STJammalan", instance = "The Sunken Temple" }
LootTracker_NPCBridge[5719] = { key = "STMorphaz", instance = "The Sunken Temple" }
LootTracker_NPCBridge[5720] = { key = "STWeaver", instance = "The Sunken Temple" }
LootTracker_NPCBridge[5721] = { key = "STDreamscythe", instance = "The Sunken Temple" }
LootTracker_NPCBridge[5722] = { key = "STHazzas", instance = "The Sunken Temple" }
LootTracker_NPCBridge[5775] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Verdan the Everliving", instance = "Wailing Caverns" }
LootTracker_NPCBridge[6109] = { key = "WorldBossesClassic", instance = "Azuregos" }
LootTracker_NPCBridge[6168] = { keys = { "RazorfenKraul1", "RazorfenKraul2" }, boss = "Blind Hunter", instance = "Razorfen Kraul" }
LootTracker_NPCBridge[6229] = { keys = { "Gnomeregan1", "Gnomeregan2" }, boss = "Crowd Pummeler 9-60", instance = "Gnomeregan" }
LootTracker_NPCBridge[6235] = { keys = { "Gnomeregan1", "Gnomeregan2" }, boss = "Electrocutioner 6000", instance = "Gnomeregan" }
LootTracker_NPCBridge[6243] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Gelihast", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[6487] = { keys = { "SMGraveyard", "SMLibrary", "SMHerod", "SMCathedral" }, boss = "Arcanist Doan", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[6910] = { key = "UldRevelosh", instance = "Uldaman" }
LootTracker_NPCBridge[6920] = { keys = { "WailingCaverns1", "WailingCaverns2" }, boss = "Deviate Faerie Dragon", instance = "Wailing Caverns" }
LootTracker_NPCBridge[7023] = { key = "UldObsidianSentinel", instance = "Uldaman" }
LootTracker_NPCBridge[7079] = { keys = { "Gnomeregan1", "Gnomeregan2" }, boss = "Viscous Fallout", instance = "Gnomeregan" }
LootTracker_NPCBridge[7206] = { key = "UldAncientStoneKeeper", instance = "Uldaman" }
LootTracker_NPCBridge[7228] = { key = "UldIronaya", instance = "Uldaman" }
LootTracker_NPCBridge[7267] = { key = "ZFChiefUkorzSandscalp", instance = "Zul'Farrak" }
LootTracker_NPCBridge[7271] = { key = "ZFWitchDoctorZumrah", instance = "Zul'Farrak" }
LootTracker_NPCBridge[7272] = { key = "ZFThekatheMartyr", instance = "Zul'Farrak" }
LootTracker_NPCBridge[7273] = { key = "ZFGahzrilla", instance = "Zul'Farrak" }
LootTracker_NPCBridge[7291] = { key = "UldGalgannFirehammer", instance = "Uldaman" }
LootTracker_NPCBridge[7354] = { keys = { "RazorfenDowns1", "RazorfenDowns2" }, boss = "Ragglesnout", instance = "Razorfen Downs" }
LootTracker_NPCBridge[7355] = { keys = { "RazorfenDowns1", "RazorfenDowns2" }, boss = "Tuten'kash", instance = "Razorfen Downs" }
LootTracker_NPCBridge[7356] = { keys = { "RazorfenDowns1", "RazorfenDowns2" }, boss = "Plaguemaw the Rotting", instance = "Razorfen Downs" }
LootTracker_NPCBridge[7357] = { keys = { "RazorfenDowns1", "RazorfenDowns2" }, boss = "Mordresh Fire Eye", instance = "Razorfen Downs" }
LootTracker_NPCBridge[7358] = { keys = { "RazorfenDowns1", "RazorfenDowns2" }, boss = "Amnennar the Coldbringer", instance = "Razorfen Downs" }
LootTracker_NPCBridge[7361] = { keys = { "Gnomeregan1", "Gnomeregan2" }, boss = "Grubbis", instance = "Gnomeregan" }
LootTracker_NPCBridge[7800] = { keys = { "Gnomeregan1", "Gnomeregan2" }, boss = "Mekgineer Thermaplugg", instance = "Gnomeregan" }
LootTracker_NPCBridge[8127] = { key = "ZFAntusul", instance = "Zul'Farrak" }
LootTracker_NPCBridge[8443] = { key = "STAvatarofHakkar", instance = "The Sunken Temple" }
LootTracker_NPCBridge[8567] = { keys = { "RazorfenDowns1", "RazorfenDowns2" }, boss = "Glutton", instance = "Razorfen Downs" }
LootTracker_NPCBridge[8983] = { key = "BRDGolemLordArgelmach", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9016] = { key = "BRDBaelGar", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9017] = { key = "BRDLordIncendius", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9019] = { key = "BRDImperatorDagranThaurissan", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9024] = { key = "BRDPyromantLoregrain", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9025] = { key = "BRDLordRoccor", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9033] = { key = "BRDGeneralAngerforge", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9056] = { key = "BRDFineousDarkvire", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9156] = { key = "BRDFlamelash", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9196] = { key = "LBRSOmokk", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[9236] = { key = "LBRSVosh", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[9237] = { key = "LBRSVoone", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[9319] = { key = "BRDHoundmaster", instance = "Blackrock Depths" }
LootTracker_NPCBridge[9568] = { key = "LBRSWyrmthalak", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[9736] = { key = "LBRSZigris", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[9816] = { key = "UBRSEmberseer", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[9938] = { key = "BRDMagmus", instance = "Blackrock Depths" }
LootTracker_NPCBridge[10000] = { key = "TrialoftheChampionBlackKnight", instance = "Trial of the Champion" }
LootTracker_NPCBridge[10184] = { key = "Onyxia_1", instance = "Onyxia's Lair" }
LootTracker_NPCBridge[10220] = { key = "LBRSHalycon", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[10264] = { key = "UBRSSolakar", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10339] = { key = "UBRSRend", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10363] = { key = "UBRSDrakkisath", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10429] = { key = "UBRSRend", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10430] = { key = "UBRSBeast", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10432] = { key = "SCHOLOVectus", instance = "Scholomance" }
LootTracker_NPCBridge[10433] = { key = "SCHOLOMarduk", instance = "Scholomance" }
LootTracker_NPCBridge[10435] = { key = "STRATMagistrateBarthilas", instance = "Stratholme" }
LootTracker_NPCBridge[10436] = { key = "STRATBaronessAnastari", instance = "Stratholme" }
LootTracker_NPCBridge[10438] = { key = "STRATMalekithePallid", instance = "Stratholme" }
LootTracker_NPCBridge[10439] = { key = "STRATRamsteintheGorger", instance = "Stratholme" }
LootTracker_NPCBridge[10502] = { key = "SCHOLOLadyIlluciaBarov", instance = "Scholomance" }
LootTracker_NPCBridge[10503] = { key = "SCHOLOJandiceBarov", instance = "Scholomance" }
LootTracker_NPCBridge[10504] = { key = "SCHOLOLordAlexeiBarov", instance = "Scholomance" }
LootTracker_NPCBridge[10505] = { key = "SCHOLOInstructorMalicia", instance = "Scholomance" }
LootTracker_NPCBridge[10506] = { key = "SCHOLOKirtonostheHerald", instance = "Scholomance" }
LootTracker_NPCBridge[10507] = { key = "SCHOLOTheRavenian", instance = "Scholomance" }
LootTracker_NPCBridge[10508] = { key = "SCHOLORasFrostwhisper", instance = "Scholomance" }
LootTracker_NPCBridge[10509] = { key = "UBRSRunewatcher", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10516] = { key = "STRATTheUnforgiven", instance = "Stratholme" }
LootTracker_NPCBridge[10558] = { key = "STRATHearthsingerForresten", instance = "Stratholme" }
LootTracker_NPCBridge[10584] = { key = "LBRSDoomhowl", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[10596] = { key = "LBRSSmolderweb", instance = "Lower Blackrock Spire" }
LootTracker_NPCBridge[10808] = { key = "STRATTimmytheCruel", instance = "Stratholme" }
LootTracker_NPCBridge[10812] = { key = "STRATBalnazzar", instance = "Stratholme" }
LootTracker_NPCBridge[10813] = { key = "STRATBalnazzar", instance = "Stratholme" }
LootTracker_NPCBridge[10899] = { key = "UBRSAnvilcrack", instance = "Upper Blackrock Spire" }
LootTracker_NPCBridge[10901] = { key = "SCHOLOLorekeeperPolkelt", instance = "Scholomance" }
LootTracker_NPCBridge[11261] = { key = "SCHOLODoctorTheolenKrastinov", instance = "Scholomance" }
LootTracker_NPCBridge[11486] = { key = "DMWPrinceTortheldrin", instance = "Dire Maul West" }
LootTracker_NPCBridge[11488] = { key = "DMWIllyannaRavenoak", instance = "Dire Maul West" }
LootTracker_NPCBridge[11489] = { key = "DMWTendrisWarpwood", instance = "Dire Maul West" }
LootTracker_NPCBridge[11490] = { key = "DMEZevrimThornhoof", instance = "Dire Maul East" }
LootTracker_NPCBridge[11496] = { key = "DMWImmolthar", instance = "Dire Maul West" }
LootTracker_NPCBridge[11501] = { key = "DMNKingGordok", instance = "Dire Maul North" }
LootTracker_NPCBridge[11502] = { key = "MCRagnaros", instance = "Molten Core" }
LootTracker_NPCBridge[11517] = { keys = { "RagefireChasm" }, boss = "Oggleflint", instance = "Ragefire Chasm" }
LootTracker_NPCBridge[11518] = { keys = { "RagefireChasm" }, boss = "Jergosh the Invoker", instance = "Ragefire Chasm" }
LootTracker_NPCBridge[11519] = { keys = { "RagefireChasm" }, boss = "Bazzalan", instance = "Ragefire Chasm" }
LootTracker_NPCBridge[11520] = { keys = { "RagefireChasm" }, boss = "Taragaman the Hungerer", instance = "Ragefire Chasm" }
LootTracker_NPCBridge[11583] = { key = "BWLNefarian1", instance = "Blackwing Lair" }
LootTracker_NPCBridge[11622] = { key = "SCHOLORattlegore", instance = "Scholomance" }
LootTracker_NPCBridge[11981] = { key = "BWLFlamegor", instance = "Blackwing Lair" }
LootTracker_NPCBridge[11982] = { key = "MCMagmadar", instance = "Molten Core" }
LootTracker_NPCBridge[11983] = { key = "BWLFiremaw", instance = "Blackwing Lair" }
LootTracker_NPCBridge[12057] = { key = "MCGarr", instance = "Molten Core" }
LootTracker_NPCBridge[12118] = { key = "MCLucifron", instance = "Molten Core" }
LootTracker_NPCBridge[12201] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Princess Theradras", instance = "Maraudon" }
LootTracker_NPCBridge[12203] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Landslide", instance = "Maraudon" }
LootTracker_NPCBridge[12225] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Celebras the Cursed", instance = "Maraudon" }
LootTracker_NPCBridge[12236] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Lord Vyletongue", instance = "Maraudon" }
LootTracker_NPCBridge[12237] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Meshlok the Harvester", instance = "Maraudon" }
LootTracker_NPCBridge[12258] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Razorlash", instance = "Maraudon" }
LootTracker_NPCBridge[12259] = { key = "MCGehennas", instance = "Molten Core" }
LootTracker_NPCBridge[12264] = { key = "MCShazzrah", instance = "Molten Core" }
LootTracker_NPCBridge[12876] = { keys = { "BlackfathomDeeps1", "BlackfathomDeeps2" }, boss = "Baron Aquanis", instance = "Blackfathom Deeps" }
LootTracker_NPCBridge[13280] = { key = "DMEHydro", instance = "Dire Maul East" }
LootTracker_NPCBridge[13282] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Noxxion", instance = "Maraudon" }
LootTracker_NPCBridge[13596] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Rotgrip", instance = "Maraudon" }
LootTracker_NPCBridge[13601] = { keys = { "Maraudon1", "Maraudon2" }, boss = "Tinkerer Gizlock", instance = "Maraudon" }
LootTracker_NPCBridge[14020] = { key = "BWLChromaggus", instance = "Blackwing Lair" }
LootTracker_NPCBridge[14321] = { key = "DMNGuardFengus", instance = "Dire Maul North" }
LootTracker_NPCBridge[14322] = { key = "DMNStomperKreeg", instance = "Dire Maul North" }
LootTracker_NPCBridge[14323] = { key = "DMNGuardSlipkik", instance = "Dire Maul North" }
LootTracker_NPCBridge[14325] = { key = "DMNCaptainKromcrush", instance = "Dire Maul North" }
LootTracker_NPCBridge[14326] = { key = "DMNGuardMoldar", instance = "Dire Maul North" }
LootTracker_NPCBridge[14327] = { key = "DMELethtendris", instance = "Dire Maul East" }
LootTracker_NPCBridge[14601] = { key = "BWLEbonroc", instance = "Blackwing Lair" }
LootTracker_NPCBridge[14834] = { key = "ZGHakkar", instance = "Zul'Gurub" }
LootTracker_NPCBridge[14887] = { key = "DYsondre", instance = "Emerald Dragons" }
LootTracker_NPCBridge[14888] = { key = "DLethon", instance = "Emerald Dragons" }
LootTracker_NPCBridge[14889] = { key = "DEmeriss", instance = "Emerald Dragons" }
LootTracker_NPCBridge[14890] = { key = "DTaerar", instance = "Emerald Dragons" }
LootTracker_NPCBridge[15114] = { key = "ZGGahzranka", instance = "Zul'Gurub" }
LootTracker_NPCBridge[15299] = { key = "AQ40Viscidus", instance = "Temple of Ahn'Qiraj" }
LootTracker_NPCBridge[15340] = { key = "AQ20Moam", instance = "Ruins of Ahn'Qiraj" }
LootTracker_NPCBridge[15348] = { key = "AQ20Kurinnaxx", instance = "Ruins of Ahn'Qiraj" }
LootTracker_NPCBridge[15517] = { key = "AQ40Ouro", instance = "Temple of Ahn'Qiraj" }
LootTracker_NPCBridge[15589] = { key = "AQ40CThun", instance = "Temple of Ahn'Qiraj" }
LootTracker_NPCBridge[15687] = { key = "KaraMoroes", instance = "Karazhan" }
LootTracker_NPCBridge[15688] = { key = "KaraIllhoof", instance = "Karazhan" }
LootTracker_NPCBridge[15689] = { key = "KaraNetherspite", instance = "Karazhan" }
LootTracker_NPCBridge[15690] = { key = "KaraPrince", instance = "Karazhan" }
LootTracker_NPCBridge[15727] = { key = "AQ40CThun", instance = "Temple of Ahn'Qiraj" }
LootTracker_NPCBridge[15928] = { key = "Naxx80Thaddius", instance = "Naxxramas" }
LootTracker_NPCBridge[15931] = { key = "Naxx80Grobbulus", instance = "Naxxramas" }
LootTracker_NPCBridge[15932] = { key = "Naxx80Gluth1", instance = "Naxxramas" }
LootTracker_NPCBridge[15936] = { key = "Naxx80Heigan", instance = "Naxxramas" }
LootTracker_NPCBridge[15952] = { key = "Naxx80Maexxna", instance = "Naxxramas" }
LootTracker_NPCBridge[15953] = { key = "Naxx80Faerlina", instance = "Naxxramas" }
LootTracker_NPCBridge[15954] = { key = "Naxx80Noth", instance = "Naxxramas" }
LootTracker_NPCBridge[15956] = { key = "Naxx80AnubRekhan", instance = "Naxxramas" }
LootTracker_NPCBridge[15989] = { key = "Naxx80Sapphiron", instance = "Naxxramas" }
LootTracker_NPCBridge[15990] = { key = "Naxx80KelThuzad", instance = "Naxxramas" }
LootTracker_NPCBridge[16011] = { key = "Naxx80Loatheb", instance = "Naxxramas" }
LootTracker_NPCBridge[16028] = { key = "Naxx80Patchwerk", instance = "Naxxramas" }
LootTracker_NPCBridge[16060] = { key = "Naxx80Gothik", instance = "Naxxramas" }
LootTracker_NPCBridge[16061] = { key = "Naxx80Razuvious", instance = "Naxxramas" }
LootTracker_NPCBridge[16063] = { key = "Naxx80FourHorsemen", instance = "Naxxramas" }
LootTracker_NPCBridge[16064] = { key = "Naxx80FourHorsemen", instance = "Naxxramas" }
LootTracker_NPCBridge[16065] = { key = "Naxx80FourHorsemen", instance = "Naxxramas" }
LootTracker_NPCBridge[16457] = { key = "KaraMaiden", instance = "Karazhan" }
LootTracker_NPCBridge[16524] = { key = "KaraAran", instance = "Karazhan" }
LootTracker_NPCBridge[17225] = { key = "KaraNightbane", instance = "Karazhan" }
LootTracker_NPCBridge[17257] = { key = "HCMagtheridon", instance = "Magtheridon's Lair" }
LootTracker_NPCBridge[17307] = { key = "HCRampVazruden", instance = "Hellfire Ramparts" }
LootTracker_NPCBridge[17380] = { key = "HCFurnaceBroggok", instance = "The Blood Furnace" }
LootTracker_NPCBridge[17537] = { key = "HCRampVazruden", instance = "Hellfire Ramparts" }
LootTracker_NPCBridge[17711] = { key = "WorldBossesBC", instance = "Kazzak" }
LootTracker_NPCBridge[17767] = { key = "MountHyjalWinterchill", instance = "Battle for Mount Hyjal" }
LootTracker_NPCBridge[17770] = { key = "CFRUnderHungarfen", instance = "The Underbog" }
LootTracker_NPCBridge[17808] = { key = "MountHyjalAnetheron", instance = "Battle for Mount Hyjal" }
LootTracker_NPCBridge[17830] = { keys = { "RagefireChasm" }, boss = "Zelemar the Wrathful", instance = "Ragefire Chasm" }
LootTracker_NPCBridge[17842] = { key = "MountHyjalAzgalor", instance = "Battle for Mount Hyjal" }
LootTracker_NPCBridge[17848] = { key = "CoTHillsbradDrake", instance = "Old Hillsbrad Foothills" }
LootTracker_NPCBridge[17862] = { key = "CoTHillsbradSkarloc", instance = "Old Hillsbrad Foothills" }
LootTracker_NPCBridge[17880] = { key = "CoTMorassTemporus", instance = "The Black Morass" }
LootTracker_NPCBridge[17881] = { key = "CoTMorassAeonus", instance = "The Black Morass" }
LootTracker_NPCBridge[17888] = { key = "MountHyjalKazrogal", instance = "Battle for Mount Hyjal" }
LootTracker_NPCBridge[17942] = { key = "CFRSlaveQuagmirran", instance = "The Slave Pens" }
LootTracker_NPCBridge[17968] = { key = "MountHyjalArchimonde", instance = "Battle for Mount Hyjal" }
LootTracker_NPCBridge[17977] = { key = "TKBotSplinter", instance = "The Botanica" }
LootTracker_NPCBridge[17980] = { key = "TKBotLaj", instance = "The Botanica" }
LootTracker_NPCBridge[18096] = { key = "CoTHillsbradHunter", instance = "Old Hillsbrad Foothills" }
LootTracker_NPCBridge[18105] = { key = "CFRUnderGhazan", instance = "The Underbog" }
LootTracker_NPCBridge[18341] = { key = "AuchManaPandemonius", instance = "Mana-Tombs" }
LootTracker_NPCBridge[18343] = { key = "AuchManaTavarok", instance = "Mana-Tombs" }
LootTracker_NPCBridge[18708] = { key = "AuchShadowMurmur", instance = "Shadow Labyrinth" }
LootTracker_NPCBridge[18831] = { key = "GruulsLairHighKingMaulgar", instance = "Gruul's Lair" }
LootTracker_NPCBridge[18832] = { key = "GruulsLairHighKingMaulgar", instance = "Gruul's Lair" }
LootTracker_NPCBridge[18834] = { key = "GruulsLairHighKingMaulgar", instance = "Gruul's Lair" }
LootTracker_NPCBridge[18835] = { key = "GruulsLairHighKingMaulgar", instance = "Gruul's Lair" }
LootTracker_NPCBridge[18836] = { key = "GruulsLairHighKingMaulgar", instance = "Gruul's Lair" }
LootTracker_NPCBridge[19044] = { key = "GruulGruul", instance = "Gruul's Lair" }
LootTracker_NPCBridge[19514] = { key = "TKEyeAlar", instance = "Tempest Keep" }
LootTracker_NPCBridge[19516] = { key = "TKEyeVoidReaver", instance = "Tempest Keep" }
LootTracker_NPCBridge[19622] = { key = "TKEyeKaelthas", instance = "Tempest Keep" }
LootTracker_NPCBridge[21217] = { key = "CFRSerpentLurker", instance = "Serpentshrine Cavern" }
LootTracker_NPCBridge[22841] = { key = "BTAkama", instance = "Black Temple" }
LootTracker_NPCBridge[22871] = { key = "BTGorefiend", instance = "Black Temple" }
LootTracker_NPCBridge[22898] = { key = "BTSupremus", instance = "Black Temple" }
LootTracker_NPCBridge[22917] = { key = "BTIllidanStormrage", instance = "Black Temple" }
LootTracker_NPCBridge[23035] = { key = "AuchSethekkRavenGod", instance = "Sethekk Halls" }
LootTracker_NPCBridge[23574] = { key = "ZAAkilZon", instance = "Zul'Aman" }
LootTracker_NPCBridge[23576] = { key = "ZANalorakk", instance = "Zul'Aman" }
LootTracker_NPCBridge[23577] = { key = "ZAHalazzi", instance = "Zul'Aman" }
LootTracker_NPCBridge[23578] = { key = "ZAJanAlai", instance = "Zul'Aman" }
LootTracker_NPCBridge[23682] = { key = "HeadlessHorseman", instance = "Scarlet Monastery" }
LootTracker_NPCBridge[23863] = { key = "ZAZuljin", instance = "Zul'Aman" }
LootTracker_NPCBridge[23872] = { key = "CorenDirebrew", instance = "Blackrock Depths" }
LootTracker_NPCBridge[23953] = { key = "UtgardeKeepKeleseth", instance = "Utgarde Keep" }
LootTracker_NPCBridge[23954] = { key = "UtgardeKeepIngvar", instance = "Utgarde Keep" }
LootTracker_NPCBridge[23980] = { key = "UtgardeKeepIngvar", instance = "Utgarde Keep" }
LootTracker_NPCBridge[24664] = { key = "SMTKaelthas", instance = "Magisters' Terrace" }
LootTracker_NPCBridge[24744] = { key = "SMTVexallus", instance = "Magisters' Terrace" }
LootTracker_NPCBridge[24850] = { key = "SPKalecgos", instance = "Sunwell Plateau" }
LootTracker_NPCBridge[24882] = { key = "SPBrutallus", instance = "Sunwell Plateau" }
LootTracker_NPCBridge[25038] = { key = "SPFelmyst", instance = "Sunwell Plateau" }
LootTracker_NPCBridge[25315] = { key = "SPKiljaeden", instance = "Sunwell Plateau" }
LootTracker_NPCBridge[25740] = { key = "LordAhune", instance = "The Slave Pens" }
LootTracker_NPCBridge[25741] = { key = "SPMuru", instance = "Sunwell Plateau" }
LootTracker_NPCBridge[26529] = { key = "CoTStratholmeMeathook", instance = "The Culling of Stratholme" }
LootTracker_NPCBridge[26530] = { key = "CoTStratholmeSalramm", instance = "The Culling of Stratholme" }
LootTracker_NPCBridge[26532] = { key = "CoTStratholmeEpoch", instance = "The Culling of Stratholme" }
LootTracker_NPCBridge[26533] = { key = "CoTStratholmeMalGanis", instance = "The Culling of Stratholme" }
LootTracker_NPCBridge[26630] = { key = "DrakTharonKeepTrollgore", instance = "Drak'Tharon Keep" }
LootTracker_NPCBridge[26631] = { key = "DrakTharonKeepNovos", instance = "Drak'Tharon Keep" }
LootTracker_NPCBridge[26632] = { key = "DrakTharonKeepTharonja", instance = "Drak'Tharon Keep" }
LootTracker_NPCBridge[26687] = { key = "UPPalehoof", instance = "Utgarde Pinnacle" }
LootTracker_NPCBridge[26693] = { key = "UPSkadi", instance = "Utgarde Pinnacle" }
LootTracker_NPCBridge[26723] = { key = "TheNexusKeristrasza", instance = "The Nexus" }
LootTracker_NPCBridge[26731] = { key = "TheNexusTelestra", instance = "The Nexus" }
LootTracker_NPCBridge[26763] = { key = "TheNexusAnomalus", instance = "The Nexus" }
LootTracker_NPCBridge[26794] = { key = "TheNexusOrmorok", instance = "The Nexus" }
LootTracker_NPCBridge[26861] = { key = "UPYmiron", instance = "Utgarde Pinnacle" }
LootTracker_NPCBridge[27447] = { key = "OcuCloudstrider", instance = "The Oculus" }
LootTracker_NPCBridge[27483] = { key = "DrakTharonKeepKingDred", instance = "Drak'Tharon Keep" }
LootTracker_NPCBridge[27654] = { key = "OcuDrakos", instance = "The Oculus" }
LootTracker_NPCBridge[27655] = { key = "OcuUrom", instance = "The Oculus" }
LootTracker_NPCBridge[27656] = { key = "OcuEregos", instance = "The Oculus" }
LootTracker_NPCBridge[27975] = { key = "HallsofStoneMaiden", instance = "Halls of Stone" }
LootTracker_NPCBridge[27977] = { key = "HallsofStoneKrystallus", instance = "Halls of Stone" }
LootTracker_NPCBridge[27978] = { key = "HallsofStoneSjonnir", instance = "Halls of Stone" }
LootTracker_NPCBridge[28546] = { key = "HallsofLightningIonar", instance = "Halls of Lightning" }
LootTracker_NPCBridge[28586] = { key = "HallsofLightningBjarngrim", instance = "Halls of Lightning" }
LootTracker_NPCBridge[28587] = { key = "HallsofLightningVolkhan", instance = "Halls of Lightning" }
LootTracker_NPCBridge[28684] = { key = "AzjolNerubKrikthir", instance = "Azjol-Nerub" }
LootTracker_NPCBridge[28859] = { key = "Malygos", instance = "The Eye of Eternity" }
LootTracker_NPCBridge[28860] = { key = "Sartharion", instance = "Obsidian Sanctum" }
LootTracker_NPCBridge[28921] = { key = "AzjolNerubHadronox", instance = "Azjol-Nerub" }
LootTracker_NPCBridge[28923] = { key = "HallsofLightningLoken", instance = "Halls of Lightning" }
LootTracker_NPCBridge[29120] = { key = "AzjolNerubAnubarak", instance = "Azjol-Nerub" }
LootTracker_NPCBridge[29266] = { key = "VioletHoldXevozz", instance = "The Violet Hold" }
LootTracker_NPCBridge[29281] = { key = "UPSorrowgrave", instance = "Utgarde Pinnacle" }
LootTracker_NPCBridge[29304] = { key = "GundrakSladran", instance = "Gundrak" }
LootTracker_NPCBridge[29305] = { key = "GundrakMoorabi", instance = "Gundrak" }
LootTracker_NPCBridge[29306] = { key = "GundrakGaldarah", instance = "Gundrak" }
LootTracker_NPCBridge[29308] = { key = "AhnkahetTaldaram", instance = "Ahn'kahet: The Old Kingdom" }
LootTracker_NPCBridge[29309] = { key = "AhnkahetNadox", instance = "Ahn'kahet: The Old Kingdom" }
LootTracker_NPCBridge[29310] = { key = "AhnkahetJedoga", instance = "Ahn'kahet: The Old Kingdom" }
LootTracker_NPCBridge[29311] = { key = "AhnkahetVolazj", instance = "Ahn'kahet: The Old Kingdom" }
LootTracker_NPCBridge[29312] = { key = "VioletHoldLavanthor", instance = "The Violet Hold" }
LootTracker_NPCBridge[29313] = { key = "VioletHoldIchoron", instance = "The Violet Hold" }
LootTracker_NPCBridge[29314] = { key = "VioletHoldZuramat", instance = "The Violet Hold" }
LootTracker_NPCBridge[29315] = { key = "VioletHoldErekem", instance = "The Violet Hold" }
LootTracker_NPCBridge[29316] = { key = "VioletHoldMoragg", instance = "The Violet Hold" }
LootTracker_NPCBridge[29932] = { key = "GundrakEckHEROIC", instance = "Gundrak" }
LootTracker_NPCBridge[30258] = { key = "AhnkahetAmanitarHEROIC", instance = "Ahn'kahet: The Old Kingdom" }
LootTracker_NPCBridge[30549] = { key = "Naxx80FourHorsemen", instance = "Naxxramas" }
LootTracker_NPCBridge[31125] = { key = "VaultofArchavonArchavon1", instance = "Vault of Archavon" }
LootTracker_NPCBridge[31134] = { key = "VioletHoldCyanigosa", instance = "The Violet Hold" }
LootTracker_NPCBridge[32845] = { key = "UlduarHodir", instance = "Ulduar" }
LootTracker_NPCBridge[32857] = { key = "UlduarIronCouncil", instance = "Ulduar" }
LootTracker_NPCBridge[32865] = { key = "UlduarThorim", instance = "Ulduar" }
LootTracker_NPCBridge[32867] = { key = "UlduarIronCouncil", instance = "Ulduar" }
LootTracker_NPCBridge[32871] = { key = "UlduarAlgalon", instance = "Ulduar" }
LootTracker_NPCBridge[32906] = { key = "UlduarFreya", instance = "Ulduar" }
LootTracker_NPCBridge[32926] = { key = "UlduarHodir", instance = "Ulduar" }
LootTracker_NPCBridge[32927] = { key = "UlduarIronCouncil", instance = "Ulduar" }
LootTracker_NPCBridge[32930] = { key = "UlduarKologarn", instance = "Ulduar" }
LootTracker_NPCBridge[33113] = { key = "UlduarLeviathan", instance = "Ulduar" }
LootTracker_NPCBridge[33118] = { key = "UlduarIgnis", instance = "Ulduar" }
LootTracker_NPCBridge[33186] = { key = "UlduarRazorscale", instance = "Ulduar" }
LootTracker_NPCBridge[33271] = { key = "UlduarVezax", instance = "Ulduar" }
LootTracker_NPCBridge[33288] = { key = "UlduarYoggSaron", instance = "Ulduar" }
LootTracker_NPCBridge[33293] = { key = "UlduarDeconstructor", instance = "Ulduar" }
LootTracker_NPCBridge[33432] = { key = "UlduarMimiron", instance = "Ulduar" }
LootTracker_NPCBridge[33515] = { key = "UlduarAuriaya", instance = "Ulduar" }
LootTracker_NPCBridge[33993] = { key = "VaultofArchavonEmalon1", instance = "Vault of Archavon" }
LootTracker_NPCBridge[34496] = { key = "TrialoftheCrusaderTwinValkyrs_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34497] = { key = "TrialoftheCrusaderTwinValkyrs_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34564] = { key = "TrialoftheCrusaderAnubarak_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34780] = { key = "TrialoftheCrusaderLordJaraxxus_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34796] = { key = "TrialoftheCrusaderNorthrendBeasts_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34797] = { key = "TrialoftheCrusaderNorthrendBeasts_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34799] = { key = "TrialoftheCrusaderNorthrendBeasts_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[34928] = { key = "TrialoftheChampionConfessorPaletress", instance = "Trial of the Champion" }
LootTracker_NPCBridge[35013] = { key = "VaultofArchavonKoralon1_A", instance = "Vault of Archavon" }
LootTracker_NPCBridge[35119] = { key = "TrialoftheChampionEadricthePure", instance = "Trial of the Champion" }
LootTracker_NPCBridge[35144] = { key = "TrialoftheCrusaderNorthrendBeasts_A", instance = "Trial of the Crusader" }
LootTracker_NPCBridge[35451] = { key = "TrialoftheChampionBlackKnight", instance = "Trial of the Champion" }
LootTracker_NPCBridge[36494] = { key = "PoSGarfrost", instance = "Pit of Saron" }
LootTracker_NPCBridge[36497] = { key = "FoSBronjahm", instance = "The Forge of Souls" }
LootTracker_NPCBridge[36502] = { key = "FoSDevourer", instance = "The Forge of Souls" }
LootTracker_NPCBridge[36597] = { key = "ICCLichKing", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36612] = { key = "ICCLordMarrowgar", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36626] = { key = "ICCFestergut", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36627] = { key = "ICCRotface", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36658] = { key = "PoSTyrannus", instance = "Pit of Saron" }
LootTracker_NPCBridge[36661] = { key = "PoSTyrannus", instance = "Pit of Saron" }
LootTracker_NPCBridge[36678] = { key = "ICCPutricide", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36789] = { key = "ICCValithria", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36853] = { key = "ICCSindragosa", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[36855] = { key = "ICCLadyDeathwhisper", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[37813] = { key = "ICCSaurfang", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[37955] = { key = "ICCLanathel", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[37970] = { key = "ICCCouncil", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[37972] = { key = "ICCCouncil", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[37973] = { key = "ICCCouncil", instance = "Icecrown Citadel" }
LootTracker_NPCBridge[38112] = { key = "HoRFalric", instance = "Halls of Reflection" }
LootTracker_NPCBridge[38113] = { key = "HoRMarwyn", instance = "Halls of Reflection" }
LootTracker_NPCBridge[38433] = { key = "VaultofArchavonToravon1", instance = "Vault of Archavon" }
LootTracker_NPCBridge[39863] = { key = "Halion", instance = "Ruby Sanctum" }
